### ISSUE TITLE
Can't connect Early Bound Generator using 8.1 or 8.2 versions of crmsvcutil

### ISSUE THREAD

**Issue by polshgiant** [daryllabar/DLaB.Xrm.XrmToolBoxTools#78] opened 2017-01-07 04:13 UTC
Even if I start from scratch with a brand new toolbox, I can't connect.  I spent hours troubleshooting and eventually figured out that if I reverted to a version that had the 8.0.x version of crmsvcutil, it would connect.  

My org is on-prem, 2016 (8.1), no IFD.  Using the toolbox, I tried with all manners of connection types (current creds, connection string, explicit creds).  I eventually took the toolbox out of the picture and just started troubleshooting using the command line string generated by the tool.  I almost pulled my hair out messing with the parameters and eventually went down the path of reverting my dlls.  

If by chance you have a 2016 on-prem org available, can you please do me a sanity check and see if you can connect the tool to it using a version of crmsvcutil greater than 8.0?  Am I going crazy?

**Comment by daryllabar** [comment] 2017-01-07 04:35
I wish I did.  I have an IFD Version that works... If you do the user interactive mode, does that work for you?

**Comment by polshgiant** [comment] 2017-01-07 05:09
Interactive mode works with the 8.0.x version, but not with 8.2.  One thing I noticed is that when I run 8.2 with logging turned on, I see this in the output:

> crmsvcutil.exe Information: 0 : Microsoft.Crm.Services.Utility.ICommandLineArgumentSource.OnUnknownArgument: Found unknown argument /CONNECTIONSTRING.
crmsvcutil.exe Information: 0 : Microsoft.Crm.Services.Utility.ICommandLineArgumentSource.OnUnknownArgument: Found unknown argument /INTERACTIVELOGIN.

Does interactive work for you using the 8.2 version?

**Comment by somefella123** [comment] 2017-03-01 10:43
I suspect EBG isn't working for anyone on 8.2... if you run ILSpy over CRMSvcUtil, it looks like the ConnectionString parameter has been dropped in favour of /url, /username and /password parameters. (I've just started trying to use it and am hitting exactly this issue).

**Comment by daryllabar** [comment] 2017-03-02 18:11
@somefella123 how do you know these have been removed?

**Comment by somefella123** [comment] 2017-03-02 18:33
Just by downloading the different versions from the nuget package feed and comparing... May be an accidental regression so keep an eye on the next version, but right now the latest version doesn't have those parameters. They were there in 8.2.0.1.

**Comment by daryllabar** [comment] 2017-03-02 18:38
I don't want to be creating work-a-rounds for issues that are due to bugs in the tooling.  If the URL parameters are unable to work due to the newest version of the CrmSvcUtil not working, please submit a ticket through your office 365 admin.  Microsoft should offer support on what they have documented.  As a work around, try manually replacing the CrmSvcUtil with an older version.

**Comment by daryllabar** [comment] 2017-03-02 19:19
Ok, just got word back from Microsoft, that the have an issue with the Nuget Package, and will be rolling out an 8.2.0.3 version that should fix this.  I'll update it when I'm notified.

**Comment by daryllabar** [comment] 2017-03-03 13:59
Newest version downloaded and built.  Can someone test this version?  [EarlyBoundGenerator.zip](https://drive.google.com/uc?export=download&id=0B0By9PBv_3cDaWE2ZGVtbV9kWVk)

**Comment by daryllabar** [comment] 2017-03-03 14:59
This should be fixed in 1.2017.3.3 now!  Let me know if it's not.

**Closed by daryllabar** 2017-03-03 14:59 UTC

**Comment by bwmodular** [comment] 2017-03-09 15:59
Not working for me, I'm afraid.
Version 1.2017.3.3 connecting to CRM 2015 On Prem.

Connection to CRM fails:
Unable to Login to Dynamics CRM
and when it tries to run in Interactive mode it complains about missing tooling files...

I've uploaded a file with the output in case it helps.
The 
[EarlyBoundErrors.txt](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/831523/EarlyBoundErrors.txt)

**Comment by daryllabar** [comment] 2017-03-09 16:39
THanks @bwmodular  for reporint.   I have a fix for this, but the OptionSets aren't getting generated created with the latest version of the CrmSrvUtil.  I'm still waiting on MS to see if that is what they intended, or if they have another bug.

**Comment by bwmodular** [comment] 2017-03-10 09:36
Ok, thanks Daryl - I look forward to hearing from you. Thanks for your help!

**Comment by daryllabar** [comment] 2017-03-11 19:54
Just an update on this.  MS is doing some additional investigation.  At this point in time they've elevated it to preventing the next version of the SDK to be released.  We'll have to continue and wait.

**Comment by bwmodular** [comment] 2017-03-13 09:00
Thanks for letting me know - I'll have to carry on using svcutil for now then!

**Comment by daryllabar** [comment] 2017-03-15 14:25
Please see https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/87 for updates.
