### ISSUE TITLE
Trying to use connection to an ifd crm throws exception

### ISSUE THREAD

**Issue by SigrunO** [daryllabar/DLaB.Xrm.XrmToolBoxTools#33] opened 2016-03-24 14:19 UTC
Hi,

unfortunatley I cannot use the tool to generate early bindings for an internet facing CRM organization.
I get the following exception, though I have connected to CRM sucessfully with XRM toolbox. Trying to exclude entities from the generated code also lets me select entites, so the connection must be working in some way.

CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Organization cannot be null or empty.
Parameter name: Organization Name
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source    : mscorlib
Method  : InvokeMethod
Date    : 15:15:56
Time    : 24.03.2016
Error   : Exception has been thrown by the target of an invocation.
Stack Trace : at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
#    at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)

Inner Exception Level 1 : 
Source  : Microsoft.Xrm.Tooling.Connector
Method  : ConnectToCrmWebService
Date    : 15:15:56
Time    : 24.03.2016
Error   : Organization cannot be null or empty.
Parameter name: Organization Name
Stack Trace : at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
#    at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)

**Comment by daryllabar** [comment] 2016-03-24 14:29
Please verify that the Command line that gets generated has the correct URL for your CRM Instance.

**Comment by SigrunO** [comment] 2016-03-24 14:43
The url looks fine. I have copied it from the command line and pasted to a browser. It is ok.

It looks somewhat like this: 

/url:"https://ourorganizationurl/XRMServices/2011/Organization.svc"

**Comment by daryllabar** [comment] 2016-03-24 14:46
Can you attempt to run the command line, in a command line?  You'll need to edit the password, since it gets "Starred" out.

**Comment by SigrunO** [comment] 2016-03-24 15:02
I have tried that and it also gives me errors. This is what I get:

CrmSvcUtil : CRM Service Utility [Version 8.0.1.7297]
© 2015 Microsoft Corporation. All rights reserved

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Organization not found. Org = XRMServices/
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM

Exiting program with exception: Exception has been thrown by the target of an invocation.
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception:
Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source    : mscorlib
Method  : InvokeMethod
Date    : 16:00:55
Time    : 24.03.2016
Error   : Exception has been thrown by the target of an invocation.
Stack Trace     : at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================
Inner Exception Level 1 :
Source  : CrmSvcUtil
Method  : Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
Date    : 16:00:55
Time    : 24.03.2016
Error   : Connection to CRM is not established. Aborting process.
Stack Trace     : at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
======================================================================================================================

**Comment by daryllabar** [comment] 2016-03-24 15:23
Looks like it is expecting it to be in the format of "https://myserver:555/MyOrg/XRMServices/2011/Organization.svc"

**Comment by SigrunO** [comment] 2016-03-24 15:25
We have used the CrmSvcUtil in the past with a url that looks like the one generated. The format you expect is not used when connecting with adfs.

**Comment by daryllabar** [comment] 2016-03-24 15:29
I feel like MS dorked this up...  Can you try to remove all of the custom plugin flags, and verify that you can connect using the standard command line:
`CrmSvcUtil.exe /url:https://myorg.crm.com:555/XRMServices/2011/Organization.svc /out:GeneratedCode.cs /username:administrator /password:p@ssword!`

If that doesn't work, then I may need to revert the version of the CrmSvcUtil that I"m using...

**Comment by SigrunO** [comment] 2016-03-24 15:43
Ok, if I use version Version 5.0.9690.3739 the following works fine (Note: no domain name specified!):

crmsvcutil.exe /url:https://servername.co.uk/XRMServices/2011/Organization.svc /out:EarlyBinding.cs /u:myname@mydomain /p:myPW /ServiceContextName:ServiceContext /Namespace:EarlyBinding

If I however use the new version of crmsvcutil, using the exact same command line, I get:

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (North America) URI is = https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (Europe, Middle East and Africa) URI is = https://disco.crm4.dynamics.com/XRMServices/20
11/Discovery.svc

**Comment by SigrunO** [comment] 2016-03-24 15:45
so do you think would it work, if I replaced crmsvcutil with an older version? I haven't tried all versions in between the one you are using (Version 8.0.1.7297) and the one I used. I am connecting to a CRM 2011

**Comment by daryllabar** [comment] 2016-03-24 16:39
It should work.  You may have to add some binding re-directs for some of the other dlls.  I'd open a support ticket with MS.   there is nothing that I know of that I'm doing specifically that takes a dependency on the CrmSrvcUtil (besides creating custom Actions)

**Comment by SigrunO** [comment] 2016-03-24 17:35
Thanks - I'll try that.

**Comment by daryllabar** [comment] 2016-03-24 19:30
Let me know if a version 8+ CRM SrvcUtil Works.

**Comment by SigrunO** [comment] 2016-03-24 22:35
I'll do some experiments when I'm back from vacation - not before April 4.

**Comment by LeszekSzejka** [comment] 2016-04-06 17:09
Same issue for me. crmsvcutil 8.0 ic causing connection issue, tested in command line

**Comment by daryllabar** [comment] 2016-04-06 18:58
@LeszekSzejka are you connecting to CRM 2011?

**Comment by SigrunO** [comment] 2016-04-07 08:22
I am also connecting to CRM 2011!

**Comment by daryllabar** [comment] 2016-04-07 10:06
If there is a CrmSvcUtil 8+ that works, let me know and I'll bundle that.  If there isn't one that works, you'll have to use a 5.? Version.  You can also feel free to open a ticket with Microsoft.  Since I idont have a CRM 2011 IFD instance to test with, there is not much I can do.

**Comment by LeszekSzejka** [comment] 2016-04-07 10:46
No, I'm using 2015 IFD environment. 
Tried with
IFD address
fullAddres/orgName/discoveryPath
fullAddres/orgName
using AD credential (default)
Using AD ccredentials provided manually.
No luck. This this needs to be 8+ issue.

Btw when building latest version from GIT the exception is thrown that: Microsoft.IdentityModel.Clients.ActiveDirectory 2.18. can not be found.

**Comment by LeszekSzejka** [comment] 2016-04-07 10:47
At this moment with 8+ I'm not able to correctly connect to IFD org at all. XrmToolbox up to invoking crmsvcutil is working fine.

**Comment by LeszekSzejka** [comment] 2016-04-07 12:30
Confirmed: with version [Version 7.1.0001.3108] command line argument (same organization as before) worked fine:  /out:somePath /url:https://serverName.com/orgName/XRMServices/2011/Organization.svc /username:domainName\leszek.szejka /password:verySecretPassword

**Comment by LeszekSzejka** [comment] 2016-04-07 12:31
Question is: can you provide plugin dedicated for latest XrmToolbox version but with references to old (2015) sdk crmsvcutil
??

**Comment by SigrunO** [comment] 2016-04-07 12:47
@LeszekSzejka: How can you connect using the new XrmToolBox? Since the authentication dialog has changed I cannot connect to my IFD organization anymore. Do you use a connection string? I am not specifying the home realm

**Comment by LeszekSzejka** [comment] 2016-04-07 12:48
I have run only commandline arguments for old (2015) crmsvcutil

**Comment by daryllabar** [comment] 2016-04-07 13:33
The Early Bound Generator just shells out to the CrmSvcUtil.  So there is no compatibility issues with Generating the code, and the XrmToolBox, as long as I can pull a userid and password from the toolbox for the CrmSvcUtil commandline.  Is using the v7 of the CrmSvcUtil a valid work around for you?

**Comment by LeszekSzejka** [comment] 2016-04-07 13:46
yes it does, at this moment i'm working at 2015 crm so version 8+ is not a compulsion

**Comment by daryllabar** [comment] 2016-04-07 14:05
@LeszekSzejka do you have the ability to open a Ticket with Microsoft?  It there is a bug, it would be nice if they would fix it.  If they have changed the string format, then I can attempt to fix it and you won't have this work around.

**Comment by LeszekSzejka** [comment] 2016-04-07 14:39
Will try, have an access to MS gold parner network

**Comment by LeszekSzejka** [comment] 2016-04-07 14:41
Nevertheless will you be able to prepare plugin version for sdk 2015 but will all latest fixes for the generator?

**Comment by daryllabar** [comment] 2016-04-07 14:57
I'm not sure if the 2015 version can connect to 2016.  You should be able to work around this issue by updating the CrmSvcUtil.exe in your "XrmToolBox\Plugins\CrmSvcUtil" to be the 2015 version, and then adding some binding redirects in the CrmSvcUtil.exe.config file.

**Comment by SigrunO** [comment] 2016-04-07 15:25
Ok, I was able to get it to work with crmsvcutil  7.1.0000.1071 and an old CrmSvcUtil.exe.config file.

**Comment by LeszekSzejka** [comment] 2016-04-07 15:29
@SigrunO XrmToolbox with plugin or only commandline ?

**Comment by SigrunO** [comment] 2016-04-07 15:40
only command line. I cannot get the Xrm Toolbox to connect to our organization with any of the releases later than the november release.

Unfortunately the command line looked more promising at first. I now get an exception. Maybe I'm missing a parameter?

System.ArgumentException: Path cannot be the empty string or all whitespace.
   at System.IO.Directory.CreateDirectory(String path)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider s
ervices)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)

**Comment by daryllabar** [comment] 2016-04-07 15:49
From the error, it looks like you're missing the /Out parameter

**Comment by LeszekSzejka** [comment] 2016-04-07 15:57
@SigrunO  use /help to get list of all possible params

**Comment by SigrunO** [comment] 2016-04-08 09:41
the /Out parameter wasn't missing. I went back and made sure that the crmsvcutil.exe.config had all the correct redirects. After some trial and error it finally worked and I was able to generate the code.
I used 1.2016.2.29 of your CrmSvcUtilExtensions dll and Version 7.1.1.3108 of CrmSvcUtil

**Comment by LeszekSzejka** [comment] 2016-04-08 12:17
@SigrunO Yes it is working but tis version does not have several fixes - I mean plugin itself

**Comment by daryllabar** [comment] 2016-04-08 12:42
So something in the 2016.3.30.1 branch is not compatible with the 7.1.1.3108 version of CrmSvcUtil?
I can attempt to determine the cause of that...

**Comment by SigrunO** [comment] 2016-04-08 14:32
I haven't had time to test with the most recent version of the generator... So I can't say anything on that for now. Hope to have some time on Monday.

**Comment by daryllabar** [comment] 2016-04-08 14:48
Thanks for your efforts!

**Comment by SigrunO** [comment] 2016-04-11 09:31
I have now tested with the most recent versions of XRM toolbox and of the generator. I used Version 7.1.1.3108 of CrmSvcUtil and everything worked. So the current way to work is to replace the CrmSvcUtil with a 7.x version.

**Comment by LeszekSzejka** [comment] 2016-04-26 08:08
Confirm, overwriting CrmSVCUtil with latest 2015 SDK and modifying CrmSvcUtil.exe.config with proper mapping works:
` <dependentAssembly>
        <assemblyIdentity name="CrmSvcUtil"
                           publicKeyToken="31bf3856ad364e35"
                           culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-8.0.0.0"
                          newVersion="7.0.0.0"/>
      </dependentAssembly>`

**Comment by vistasgp888** [comment] 2016-07-21 20:36
I'm having issues with this too.  I have tried to follow the steps that LeszekSzejka stated yet I'm getting the following:

Output file was not updated or not found!

**Comment by daryllabar** [comment] 2016-07-22 01:11
There should be more of a error message than that.  What does the whole output text show?

**Comment by vistasgp888** [comment] 2016-07-22 02:38
CRM Authentication Type Detected: Federation
Executing "C:\Users\Downloads\XrmToolBox-v.1.2016.6.29\XrmToolBox-v.1.2016.6.29\XrmToolBox\bin\Debug\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://fake.fake.com/XRMServices/2011/Organization.svc" /namespace:"fake" /out:"C:\Users\Downloads\XrmToolBox-v.1.2016.6.29\XrmToolBox-v.1.2016.6.29\XrmToolBox\bin\Debug\Plugins\CrmSvcUtil Ref\fake.cs" /servicecontextname:"fake" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"fake" /password:"fake" /domain:"fake.com" 
CrmSvcUtil : CRM Service Utility [Version 7.1.0001.3108]
c 2015 Microsoft Corporation.  All rights reserved.

Output file was not updated or not found!  C:\Users\Downloads\XrmToolBox-v.1.2016.6.29\XrmToolBox-v.1.2016.6.29\XrmToolBox\bin\Debug\Plugins\CrmSvcUtil Ref\fake.cs

**Comment by daryllabar** [comment] 2016-07-22 10:51
If you run just the command line:

> "C:\Users\Downloads\XrmToolBox-v.1.2016.6.29\XrmToolBox-v.1.2016.6.29\XrmToolBox\bin\Debug\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://fake.fake.com/XRMServices/2011/Organization.svc" /namespace:"fake" /out:"C:\Users\Downloads\XrmToolBox-v.1.2016.6.29\XrmToolBox-v.1.2016.6.29\XrmToolBox\bin\Debug\Plugins\CrmSvcUtil Ref\fake.cs" /servicecontextname:"fake" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"fake" /password:"fake" /domain:"fake.com" 

Does it error?

**Comment by vistasgp888** [comment] 2016-07-22 15:16
When I run from the command line I get:

"Could not load file or assembly 'Microsoft.xrm.sdk, version 8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.  The located assembly's manifest definition does not match the assembly reference.

**Comment by daryllabar** [comment] 2016-07-22 15:25
Is there a Microsoft.Xrm.Sdk dll in your "C:\Users\Downloads\XrmToolBox-v.1.2016.6.29\XrmToolBox-v.1.2016.6.29\XrmToolBox\bin\Debug\Plugins\CrmSvcUtil Ref\" folder?

**Comment by vistasgp888** [comment] 2016-07-24 23:40
Forgive my ignorance on this, but I have been having a hard time getting this running.

I downloaded XrmToolBox-v.1.2016.6.29 (since it has older assemblies) then I added all the projects from the DLaB.Xrm.XrmtoolBoxTools into the Plugins directory of the XrmToolBox solution, tweaked a few things and got it to compile.  I'm not seeing the EarlyBoundGenerator show up in the list of  plugins.  Do I need to add my own plugin.cs files?

Any advice on how to get to where I can debug the EarlyBoundGenerator?  Thanks!

**Comment by daryllabar** [comment] 2016-07-25 00:00
You shouldn't have to download the XrmToolBox... It should be included in a nuget package.  Did you download all of the nuget files?  

In order to debug, you should debug the project you want to debug.  I have it setup on my machine to run the XTB in my debug directory, then I attach it from there.  Kind of confusing I know.  Once the summer comes to an end, I should have time to do a video...

**Comment by vistasgp888** [comment] 2016-07-25 00:20
Thanks for the quick response Daryl.

I finally got it to work, although the first time I ran it I got the following error:
(I'm not too worried about this at the moment, I can work around for now)
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService.GenerateOptionSet(OptionSetMetadataBase optionSetMetadata, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildAttributeOptionSet(EntityMetadata entity, AttributeMetadata attribute, CodeTypeMember attributeMember, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntity(EntityMetadata entity, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntities(EntityMetadata[] entityMetadata, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildCodeDom(IOrganizationMetadata organizationMetadata, String outputNamespace, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)

Anyways, thanks for the help!

**Comment by daryllabar** [comment] 2016-07-25 00:41
Good luck!

**Comment by IDontEatSoap** [comment] 2016-08-07 23:41
This is caused as a result of this code inside the Tooling.Connector code:

`private void SetOrgnameAndOnlineRegion(Uri serviceUri)
    {
      if (serviceUri.Host.ToUpperInvariant().Contains("DYNAMICS.COM") || serviceUri.Host.ToUpperInvariant().Contains("DYNAMICS-INT.COM"))
      {
        List<string> stringList = new List<string>((IEnumerable<string>) serviceUri.Host.Split(new string[1]{ "." }, StringSplitOptions.RemoveEmptyEntries));
        this.Organization = stringList[0];
        stringList.RemoveAt(0);
        CrmOnlineDiscoveryServers discoveryServers = new CrmOnlineDiscoveryServers();
        StringBuilder stringBuilder = new StringBuilder();
        foreach (string str in stringList)
          stringBuilder.AppendFormat("{0}.", (object) str);
        string crmKey = stringBuilder.ToString().TrimEnd('.').TrimEnd('/');
        stringBuilder.Clear();
        if (!string.IsNullOrEmpty(crmKey))
        {
          CrmOnlineDiscoveryServer onlineDiscoveryServer = discoveryServers.OSDPServers.Where<CrmOnlineDiscoveryServer>((Func<CrmOnlineDiscoveryServer, bool>) (w =>
          {
            if (w.DiscoveryServer != (Uri) null)
              return w.DiscoveryServer.Host.Contains(crmKey);
            return false;
          })).FirstOrDefault<CrmOnlineDiscoveryServer>();
          if (onlineDiscoveryServer != null && !string.IsNullOrEmpty(onlineDiscoveryServer.ShortName))
            this.CrmOnlineRegion = onlineDiscoveryServer.ShortName;
        }
        this.IsOnPremOauth = false;
      }
      else
      {
        this.IsOnPremOauth = true;
        if (((IEnumerable<string>) serviceUri.Segments).Count<string>() < 2)
          return;
        this.Organization = serviceUri.Segments[1].TrimEnd('/');
      }
    }`

You can see that at the end, the baboon who coded it didn't checked for all the possible Uri combinations. So if you set your connection string as per the documentation, something like http://server/Organization, it will fail as the Uri won't have two segments.

For now, parse your connection string and pass the parameters in the full CrmServiceClient constructor directly.

**Comment by daryllabar** [comment] 2016-10-27 15:52
@IDontEatSoap didn't see this post of yours.  Since this is all run from the command line, I believe I don't have a method to pass the parameters into the CrmServiceClient Directly.  Is that correct?

**Comment by daryllabar** [comment] 2016-11-11 16:15
Would someone that is having this issue currently, please try the latest 8.2 version of the SDK files to see if it has been resolved?  I was able to procur a MS resource for resolving this if it has not already been resolved, I just need to know that it wasn't

**Comment by SigrunO** [comment] 2016-11-14 09:29
I just retested this with the latest SDK version and it still fails.

**Comment by LeszekSzejka** [comment] 2016-11-14 13:19
@SigrunO:  i had simillar issue some time ago:
- check if all CRM ports are available via firewall
- you can change CrmSvcUtill with 2015 version adn
modify crmsvcutil.exe.config file to llok for version 7.0.0.0 of the tool
instead 8.0.0.0.

It is the best workaround for now. Especially that v8 does not have any new
functionality (at least I am not aware of) except different connection
method.

**Comment by daryllabar** [comment] 2016-11-14 13:26
Thanks @SigrunO,  I'll forward that on to Microsoft.

**Comment by daryllabar** [comment] 2017-03-03 15:08
Does 1.2017.3.3 fix this issue?

**Comment by daryllabar** [comment] 2017-08-07 12:37
Haven't heard anything on this.  Closing the issue.

**Closed by daryllabar** 2017-08-07 12:37 UTC

**Comment by Abhishek9166919669** [comment] 2018-11-29 14:34
i am getting this error
![image](https://user-images.githubusercontent.com/39114448/49228728-fcefde80-f411-11e8-8a0f-0f7ad4dee17a.png)

**Comment by daryllabar** [comment] 2018-11-30 00:30
Any possibility that was just a network error?
