### ISSUE TITLE
Unable to Generate Early Bound Entities for CRM Online 2016 Org

### ISSUE THREAD

**Issue by cabreram** [daryllabar/DLaB.Xrm.XrmToolBoxTools#65] opened 2016-11-07 16:37 UTC
I receive the following error after clicking the Create Entities button, if I run the the generated crmsvcutil.exe command manually and add the switches for /username and /password the code is generated.

Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: mscorlib
Method	: InvokeMethod
Date	: 11:21:10 AM
Time	: 11/7/2016
Error	: Exception has been thrown by the target of an invocation.
Stack Trace	: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================
Inner Exception Level 1	: 
Source	: CrmSvcUtil
Method	: Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
Date	: 11:21:10 AM
Time	: 11/7/2016
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
======================================================================================================================

Output file was not updated or not found!  C:\TEMP\XrmToolBox\Plugins\CrmSvcUtil Ref\CorporateComplianceServiceContext.cs
CRM Authentication Type Detected: OnlineFederation
Executing "C:\TEMP\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://xxxx.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"CrmEarlyBound" /out:"C:\Corporate Compliance\Development\2017.02\Source\App_Code\CorporateComplianceCommon\Entities\CorporateComplianceServiceContext.cs" /servicecontextname:"CorporateComplianceServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" 
CrmSvcUtil : CRM Service Utility [Version 8.1.0.7711]
c 2015 Microsoft Corporation. All rights reserved

Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: mscorlib
Method	: InvokeMethod
Date	: 11:28:51 AM
Time	: 11/7/2016
Error	: Exception has been thrown by the target of an invocation.
Stack Trace	: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================
Inner Exception Level 1	: 
Source	: CrmSvcUtil
Method	: Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
Date	: 11:28:51 AM
Time	: 11/7/2016
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
======================================================================================================================

**Comment by daryllabar** [comment] 2016-11-07 17:10
This is failing for CRM Online?

**Comment by daryllabar** [comment] 2016-11-07 17:14
Do you have your credentials saved via the XrmToolBox?

**Comment by cabreram** [comment] 2016-11-07 18:25
Yes, this was for CRM Online and yes the credentials are saved via the XrmToolBox.  I believe the issue is because I used a connection string to store the connection info.  I created a new connection the standard way and the no longer receive the error.  I assume the code reads the username and password from the UserName and Password elements in the config file.  The ConnectionDetail when using a connection string doesn't contain those elements, it jus has a ConnectionString element that stores the connection info.

**Comment by daryllabar** [comment] 2016-11-07 18:35
So if the User name and password is not in the Connection string, how do you connect?

**Comment by cabreram** [comment] 2016-11-07 18:58
The username and password is stored in the connection string.  I haven't looked at the code the generates the crmsvcutil.exe command, but what I'm assuming is that it looks in the connectiondetail of the mscrmtools2011.config file and pulls the  data from <UserName> and <UserPassword> elements.

When a connection is created and stored using a connectionstring, the connectiondetail has all of the data in the <ConnectionString> element.  So, I guess what I'm trying to communicate is that my hunch is that the code doesn't parse out the username and password from the <ConnectionString> element to pass to the crmsvcutil.exe.

I don't need to  use a connection string, so this is just an FYI in case you want to make it a priority to have it work when storing connection information via a connection string.

**Comment by daryllabar** [comment] 2016-11-07 20:12
Thanks for the info, I'll see if I can recreate and update.

**Comment by LoveSpt** [comment] 2016-12-07 14:41
It seems that the problem is really CrmSvUtil, it is trying to connect to a url that is not the one passed as parameter for the msdos command prompt.

**Comment by lilmaster** [comment] 2016-12-21 21:12
I was able to generate by using _/connectionstring_: parameter; instead of using /url, /username, and /password. I guess crmsvcutil.exe is using Xrm tooling to connect to Dynamics 365.

**Comment by daryllabar** [comment] 2016-12-21 21:14
I've got a fix that I'm attempting to deploy.  Problem is I've created other issues as well that have broken things.... :(

**Comment by daryllabar** [comment] 2016-12-29 05:29
Can you try the newest version (1.2016.12.28) to see if it has resolved this issue?

**Comment by cabreram** [comment] 2016-12-29 14:31
The latest version did not work...this is the log from XrmToolBox

CRM Authentication Type Detected: OnlineFederation
Executing "C:\Users\CabreraM\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://xxx.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"CrmEarlyBound" /out:"C:\TEMP\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" 
CrmSvcUtil : CRM Service Utility [Version 8.2.0.749]
c 2015 Microsoft Corporation.  All rights reserved.

Output file was not updated or not found!  C:\TEMP\CrmServiceContext.cs

Executing the command from the command line shows this error:
Exiting program with exception: Value cannot be null.
Parameter name: ClientCredentials.UserName.UserName
Enable tracing and view the trace files for more information.

The command above seems to be missing the /username and /password options.  When I add them to the command and run from the command line it works.

**Comment by daryllabar** [comment] 2017-03-03 15:06
This should be fixed in 1.2017.3.3

**Closed by daryllabar** 2017-03-03 15:06 UTC
Labels: bug
